import { BarChart3, Quote, Users, FileText, ArrowUpRight } from 'lucide-react';
import { makeReportData, profileFrequencies, quoteExcerpt } from '../lib/reportData';
import { TYPE_LABELS, type Study } from '../lib/study';

function Narrative({text}:{text:string}) {
  return <div className="report-narrative">{text.split(/\n\s*\n/).filter(Boolean).map((block,index)=>{
    const lines=block.trim().replace(/\*\*/g,'').split('\n');const first=lines[0].replace(/^#+\s*/, '');
    const heading=/^(?:\d+[.)]\s*)?(?:Общая информация|Характеристики|Результаты|Принципы|Темы|Сопоставление|Выводы|Ограничения|Методология|Краткие|Аналитический|Анализ|Демографические|Аргументы|Нейтральные|Неожиданные|Противоречия|Исследовательские|Дальнейшее)/i.test(first)&&first.length<130;
    return <div key={index}>{heading&&<h4 className="mb-3 mt-6 text-lg font-bold">{first}</h4>}<p className="whitespace-pre-wrap leading-7 text-gray-700">{(heading?lines.slice(1):lines).join('\n')}</p></div>;
  })}</div>;
}
export default function ReportPreview({study:s}:{study:Study}) {
  const data=makeReportData(s);
  const sections=[['report-overview','Краткая сводка'],['report-findings','Результаты'],['report-method','Метод и источники']];
  return <article className="report-sheet" aria-label="Предпросмотр отчёта">
    <header className="report-cover"><div className="flex flex-wrap items-center justify-between gap-3"><span className="report-cover__badge">{data.preliminary?'Предварительный отчёт':'Исследовательский отчёт'}</span><span className="text-xs text-blue-100">{new Date(s.createdAt).toLocaleDateString('ru-RU')}</span></div><p className="mt-7 text-xs font-bold uppercase tracking-widest text-blue-200">{TYPE_LABELS[s.type]}</p><h2 className="mt-3 max-w-3xl text-3xl font-bold leading-tight tracking-tight sm:text-4xl">{s.topic}</h2><p className="mt-4 max-w-2xl leading-7 text-blue-100">{s.question}</p><p className="mt-7 border-t border-white/15 pt-4 text-xs leading-5 text-blue-100">Ответы смоделированы. Люди не опрашивались. Отчёт помогает уточнять гипотезы и готовить реальное исследование.</p></header>
    <div className="report-sheet__body"><div className="grid gap-3 sm:grid-cols-3">{[[Users,s.population.length,'Профилей в выборке'],[BarChart3,s.type==='qualitative'?data.included.length:s.responses.length,s.type==='qualitative'?'Интервью в отчёте':'Полученных анкет'],[FileText,s.type==='qualitative'?data.quotes.length:s.type==='quantitative'?(s.workflow==='survey'?data.survey.length:data.quotes.length):data.included.length,s.type==='qualitative'?'Сохранённых ответов':s.type==='quantitative'?(s.workflow==='survey'?'Вопросов в анкете':'Развёрнутых ответов'):'Интервью в отчёте']].map(([Icon,value,label])=>{const Glyph=Icon as typeof Users;return <div className="report-metric" key={String(label)}><Glyph size={18} className="text-blue-600"/><p className="mt-3 text-3xl font-bold">{String(value)}</p><p className="mt-1 text-xs text-gray-500">{String(label)}</p></div>;})}</div>
    <nav className="my-7 flex flex-wrap gap-2" aria-label="Разделы отчёта">{sections.map(([id,label])=><a className="report-section-link" key={id} href={`#${id}`}>{label}<ArrowUpRight size={13}/></a>)}</nav>
    <section id="report-overview" className="report-section"><p className="report-kicker">01 / Главное</p><h3 className="report-heading">Что видно из данных</h3>{data.preliminary&&<p className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">Включено {data.included.length} из {s.selectedIds.length} выбранных участников. Незавершённые интервью не анализируются.</p>}<div className="grid gap-4">{data.insights.map((fact,i)=><div className="report-finding" key={i}><span className="text-xs font-bold text-blue-600">Наблюдение {i+1}</span><h4 className="mt-2 font-semibold">{fact.title}</h4><p className="mt-2 text-sm leading-6 text-gray-600">{fact.text}</p></div>)}</div></section>
    <section id="report-findings" className="report-section"><p className="report-kicker">02 / Результаты</p><h3 className="report-heading">{data.survey.length?(s.type==='quantitative'?'Результаты анкеты':'Ответы и их объяснения'):'Темы и фрагменты интервью'}</h3>
    {data.survey.map(q=>{const total=q.distribution.reduce((n,d)=>n+d.count,0);return <div className="report-chart" key={q.id}><h4 className="font-bold">{q.text}</h4><p className="mt-1 mb-5 text-xs text-gray-500">База: {total} ответов. Каждый участник выбирал один вариант.</p>{q.distribution.map(d=>{const percent=total?d.count/total*100:0;return <div className="mb-4" key={d.option}><div className="mb-2 flex justify-between gap-4 text-sm"><span className="min-w-0 break-words">{d.option}</span><span className="shrink-0 font-bold">{percent.toLocaleString('ru-RU',{maximumFractionDigits:1})}% <span className="font-normal text-gray-400">· {d.count}</span></span></div><div className="h-2 rounded-full bg-blue-50"><div className="h-2 rounded-full bg-blue-600" style={{width:`${percent}%`}}/></div></div>;})}</div>;})}
    {s.type==='quantitative'&&!data.survey.length&&<div className="report-chart"><h4 className="font-bold">Позиции, заложенные в профили</h4><p className="mt-2 mb-5 text-xs leading-6 text-gray-500">Модельная гипотеза при создании выборки. Это не ответы анкеты и не результаты опроса людей.</p>{[...new Set(s.population.map(p=>p.opinion))].map(option=>{const count=s.population.filter(p=>p.opinion===option).length,percent=count/s.population.length*100;return <div className="mb-4" key={option}><div className="mb-2 flex justify-between gap-4 text-sm"><span>{option}</span><strong>{percent.toLocaleString('ru-RU',{maximumFractionDigits:1})}% · {count}</strong></div><div className="h-2 rounded-full bg-blue-50"><div className="h-2 rounded-full bg-blue-600" style={{width:`${percent}%`}}/></div></div>;})}</div>}
    {data.themes.map((theme,i)=><section className="report-theme" key={i}><span className="report-kicker">Тема {i+1}</span><h4 className="mt-2 text-xl font-bold">{theme.title}</h4><p className="mt-3 text-sm leading-7 text-gray-600">{theme.interpretation}</p><p className="mt-2 text-xs text-gray-400">Интерпретация модели по приведённым цитатам</p>{theme.quotes.slice(0,3).map((q,j)=><blockquote className="report-quote" key={j}><Quote size={18} className="mb-3 text-blue-600"/><p className="whitespace-pre-wrap leading-7">«{quoteExcerpt(q.quote)}»</p><footer className="mt-4 text-xs font-semibold text-blue-700">Участник №{q.respondentId} · {q.question}</footer></blockquote>)}</section>)}
    {!data.themes.length&&data.quotes.length>0&&<div className="space-y-4">{data.quotes.slice(0,4).map((q,i)=><blockquote className="report-quote" key={i}><p className="mb-3 text-xs font-semibold text-blue-700">Участник №{q.respondentId} · {q.question}</p><p className="whitespace-pre-wrap leading-7">«{quoteExcerpt(q.quote)}»</p></blockquote>)}</div>}
    {s.type==='mixed'&&<div className="report-chart"><h4 className="font-bold">Как интервью дополняют опрос</h4><p className="mt-2 text-sm leading-6 text-gray-600">Сопоставляйте ответы одного и того же участника. Фрагменты интервью раскрывают отдельные случаи и не объясняют автоматически всю выборку.</p>{data.included.map(id=><div key={id} className="mt-4 border-t border-gray-100 pt-4 text-sm"><p className="font-bold">Участник №{id}</p>{s.questionnaire.map(q=><p className="mt-1 text-gray-600" key={q.id}>{q.text}: <strong>{s.responses.find(r=>r.respondentId===id)?.answers[q.id]??'Нет ответа'}</strong></p>)}</div>)}</div>}
    {s.report&&<details open className="report-detail"><summary>Аналитические выводы и пояснения</summary><div className="mt-5"><Narrative text={s.report}/></div></details>}
    {data.quotes.length>0&&<details className="report-detail"><summary>Все сохранённые ответы · {data.quotes.length}</summary><div className="mt-5 space-y-5">{data.quotes.map((q,i)=><div key={i}><p className="text-sm font-bold">Участник №{q.respondentId} · {q.question}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-gray-600">{q.quote}</p></div>)}</div></details>}
    </section>
    <section id="report-method" className="report-section"><p className="report-kicker">03 / Основа исследования</p><h3 className="report-heading">Выборка, метод и источники</h3><div className="grid gap-4 sm:grid-cols-2">{(['gender','education'] as const).map(key=><div className="report-chart" key={key}><h4 className="mb-4 font-bold">{key==='gender'?'Пол':'Образование'}</h4>{profileFrequencies(s,key).map(([name,count])=><p className="flex justify-between gap-4 border-b border-gray-100 py-3 text-sm" key={name}><span>{name}</span><strong>{count}</strong></p>)}</div>)}</div><p className="mt-5 text-sm leading-7 text-gray-600">Профили созданы программно, ответы смоделированы индивидуально. Частоты и проценты рассчитаны из сохранённых ответов. {s.selectionReason&&`Принцип отбора: ${s.selectionReason}`}</p>{s.sources?.length?<ol className="mt-5 space-y-4">{s.sources.map((source,i)=><li className="rounded-xl bg-gray-50 p-4 text-sm" key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer" className="font-semibold text-blue-700 underline">{i+1}. {source.title}</a><p className="mt-2 leading-6 text-gray-500">{source.organization} · {source.date} · {source.geography}</p><p className="mt-1 leading-6 text-gray-600">{source.application}</p></li>)}</ol>:<p className="mt-5 text-sm text-gray-500">Проверенная статистическая основа для этого проекта не применялась.</p>}<div className="report-limitations"><h4 className="font-bold">Границы интерпретации</h4><p className="mt-2 text-sm leading-7">Синтетические ответы не являются мнениями опрошенных людей. Репрезентативность не установлена. Большая выборка не делает смоделированные ответы независимыми наблюдениями; перенос выводов на население требует реальных данных.</p></div></section>
    </div>
  </article>;
}
